import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vitest/config'
import { playwright } from '@vitest/browser-playwright'
import adapter from '@sveltejs/adapter-cloudflare'
import { sveltekit } from '@sveltejs/kit/vite'

export default defineConfig({
	plugins: [
		tailwindcss(),
		sveltekit({
			compilerOptions: {
				// Force runes mode for the project, except for libraries. Can be removed in svelte 6.
				runes: ({ filename }) =>
					filename.split(/[/\\]/).includes('node_modules') ? undefined : true,
			},

			// Builds to .svelte-kit/cloudflare — see wrangler.jsonc `main` / `assets.directory`.
			adapter: adapter({
				// Bindings from wrangler.jsonc are emulated by miniflare during `vite dev`
				// and exposed as `platform.env`. `persist` keeps local D1 data in
				// .wrangler/state, the same place `npm run db:migrate` writes to.
				platformProxy: { persist: true },
			}),

			typescript: {
				config: (config) => {
					config.include.push('../drizzle.config.ts')
					// Generated by `npm run gen` (wrangler types): Env + Workers runtime types.
					config.include.push('../worker-configuration.d.ts')
				},
			},
		}),
	],
	test: {
		expect: { requireAssertions: true },
		projects: [
			{
				extends: './vite.config.ts',
				test: {
					name: 'client',
					browser: {
						enabled: true,
						provider: playwright(),
						instances: [{ browser: 'chromium', headless: true }],
					},
					include: ['src/**/*.svelte.{test,spec}.{js,ts}'],
					exclude: ['src/lib/server/**'],
				},
			},

			{
				extends: './vite.config.ts',
				test: {
					name: 'server',
					environment: 'node',
					include: ['src/**/*.{test,spec}.{js,ts}'],
					exclude: ['src/**/*.svelte.{test,spec}.{js,ts}'],
				},
			},
		],
	},
})
