// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}

		// `Env` comes from worker-configuration.d.ts, generated by `npm run gen`.
		// Re-run it whenever the bindings in wrangler.jsonc change.
		// `ctx`, `caches` and `cf` are already declared by adapter-cloudflare's
		// ambient types — only `env` belongs here.
		interface Platform {
			env: Env
		}
	}
}

export {}
